--- 
title: "R (RAMA course)"
author: "Jonathan D. Rosenblatt"
date: '`r Sys.Date()`'
bibliography: bib.bib
description: Class notes for the R course at the BGU's IE&M dept.
documentclass: book
keywords: "Rstats, Statistics"

link-citations: yes
biblio-style: apalike
---

```{r knitr defaults, echo=FALSE}
knitr::opts_chunk$set(out.width='50%')
knitr::opts_chunk$set(cache = TRUE)
set.seed(1)
```




# Preface

This book accompanies an R programming workshop.
It has several purposes:

- Help me organize and document the course material.
- Help students during class so that they may focus on listening and not writing.
- Help students after class, so that they may self-study.

I will be enormously grateful to whoever decides to share with me any mistakes found.

I hope the reader will find this text interesting and useful. 

For reproducing my results you will want to run `set.seed(1)`.





## Notation Conventions

In this text we use the following conventions:
Lower case $x$ may be a vector or a scalar, random of fixed, as implied by the context. 
Upper case $A$ will stand for matrices. 
Equality $=$ is an equality, and $:=$ is a definition.
Norm functions are denoted with $\Vert x \Vert$ for vector norms, and $\Vert A \Vert$ for matrix norms. 
The type of norm is indicated in the subscript; e.g. $\Vert x \Vert_2$ for the Euclidean ($l_2$) norm.
Tag, $x'$ is a transpose. 
The distribution of a random vector is $\sim$.



## Acknowledgements

I have consulted many people during the writing of this text.
I would like to thank [Yoav Kessler](https://kesslerlab.wordpress.com/), [Lena Novack](http://fohs.bgu.ac.il/research/profileBrief.aspx?id=VeeMVried), Efrat Vilenski, Ron Sarafian, and Liad Shekel in particular, for their valuable inputs. 
